openapi:
  service:
    title: order-service doc
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /order-service/v3/api-docs
  swagger-ui:
    path: /order-service/swagger-ui.html